# Generated by Django 5.1.7 on 2025-03-11 20:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdAt', models.DateField(auto_now=True)),
                ('expiredDate', models.DateField(default=datetime.datetime(2025, 3, 21, 20, 42, 6, 596550, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeNo', models.CharField(max_length=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('floorNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('requestDate', models.DateField(auto_now=True)),
                ('tenantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('officeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_management.office')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('monthlyRent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('officeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_management.office')),
                ('tenantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateField()),
                ('paidDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_management.rental')),
            ],
        ),
    ]
