# Generated by Django 5.1.7 on 2025-03-12 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiredDate',
            field=models.DateField(default=datetime.datetime(2025, 3, 22, 7, 19, 19, 441309, tzinfo=datetime.timezone.utc)),
        ),
    ]
